services:
  web:
    build:
      context: . 
      dockerfile: domain-monitor-docker/.docker/Dockerfile
    container_name: domain-monitor-web
    env_file:
      - domain-monitor-docker/.env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:10.11 # Using a stable LTS version
    container_name: domain-monitor-mariadb
    restart: unless-stopped
    env_file:
      - domain-monitor-docker/.env
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    container_name: domain-monitor-pma
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  dbdata: